### PR TITLE
Fix suspense bugs

### LINKED ISSUE #57: Bug: Suspense Data undefined Race Condition
I'm not sure if this is a bug, or if this behavior is intended, but I was running into an issue with the line of code below. 

So, I'm using `useSWR(`/api/users/${id}`, fetch, {suspense: true})` where the key is dynamic based on the id of the object I want to get (in this contrived example the user's id). 

My code looks something like this exampled:

```
function useUser(id) {
  const user = useSWR(`/api/users/${id}`, fetch, {suspense: true})
  console.log(user)
  return user
}
```

When this hook is called multiple times with different IDs, the logs would look like this:

```
// render 1 with user id 1
{ id:1 }
// render 2 with user id 2
undefined
// render 3
{ id: 2 }
```

The reason behind this is the two LOC referenced below.

So, my question is, in render 2 on L342 `typeof data = Object`, not undefined because the data is reset on line 358 (afterwards). Should there be a line before line 342 that checks to see if the `keyRef.current` and the new `key` are then different and reset data there so that the revalidate can happen immediately? 

I quickly implemented this locally and this fixed my issue and prevented render 2 happening where the data was undefined.

Thanks! Loving this library so far.

https://github.com/zeit/swr/blob/9b51b7d066335d7249d114e2b9a2cb5d633795b6/src/use-swr.ts#L342
https://github.com/zeit/swr/blob/9b51b7d066335d7249d114e2b9a2cb5d633795b6/src/use-swr.ts#L358

### LINKED ISSUE #66: BUG: Infinite loop with suspense on rejected promise
See: https://codesandbox.io/s/swr-playground-zloyr

Steps to reproduce:
- Use SWR
- Set suspense to true
- Set shouldRetryOnError to false
- Reject HTTP request (or just promise)

Actual result:
Endless loop of retrying

Expected result:
Error boundary should catch error'ed promise

### PR DESCRIPTION
**Pull request by quietshu**
Bug fixes
- fixed #57 and added a test case for it
- fixed #66 and added a test case for it

Also
- introduced cache for errors to support suspense
- changed `noDedupe` to `dedupe` (undocumented API), which is more clear and removes 1 hook inside  (`useCallback`)
- improved code readability

### CODE REVIEW

File: src/use-swr.ts [hunk 1]
```diff
@@ -361,21 +413,60 @@ function useSWR<Data = any, Error = any>(
...
       }
     }
   }, [key, config.refreshInterval, revalidate])
 
-  // suspense (client side only)
-  if (config.suspense && typeof data === 'undefined') {
-    if (typeof window !== 'undefined') {
+  // suspense
+  if (config.suspense) {
+    if (IS_SERVRE)
```
Comment (pacocoursey) [inline src/use-swr.ts]:
```suggestion
    if (IS_SERVER)
```

File: src/use-swr.ts [hunk 2]
```diff
@@ -33,26 +33,34 @@ import SWRConfigContext from './swr-config-context'
 import isDocumentVisible from './libs/is-document-visible'
 import useHydration from './libs/use-hydration'
 
+const IS_SERVRE = typeof window === 'undefined'
```
Comment (pacocoursey) [inline src/use-swr.ts]:
```suggestion
const IS_SERVER = typeof window === 'undefined'
```

File: src/use-swr.ts [hunk 3]
```diff
@@ -361,21 +413,60 @@ function useSWR<Data = any, Error = any>(
...
+        // to get the promise
         revalidate()
       }
-      throw CONCURRENT_PROMISES[key]
+
+      if (
+        CONCURRENT_PROMISES[key] &&
+        typeof CONCURRENT_PROMISES[key].then === 'function'
+      ) {
+        console.log(CONCURRENT_PROMISES[key], key)
```
Comment (quietshu) [inline src/use-swr.ts]:
```suggestion
```
