### PR TITLE
Fix suspense hanging

### LINKED ISSUE #46: Suspense is not resolved and the requests are looping
```javascript
import React, { Suspense } from 'react';
import useSWR from '@zeit/swr'

function StarWarsSuspense() {
  return (
    <Suspense fallback={<div>loading ...</div>}>
      <StarWars />
    </Suspense>
  )
}

function StarWars() {
  const { data } = useSWR('http://swquotesapi.digitaljedi.dk/api/SWQuote/RandomStarWarsQuote', fetch, { suspense: true });

  return (
    <div>
      {data.starWarsQuote}
    </div>
  );
}

export default StarWarsSuspense;
```
With this code, i never get the final component, the placeholder stay forever, looking on chrome developer console, the requests are looping.

I made this code using the readme example, i tried change de fetch function to a random promise to see if i get out of fallback, without no results.

I doing something wrong or this is really something that should not happen ?

### PR DESCRIPTION
**Pull request by quietshu**
The problem is caused by `useHydration`. 

When enabling SSR with frameworks like Next.js, we have to match the SSRed result with the client rendered result on hydration, so we skipped from reading the cache.  
But when suspense is enabled, we need to read from cache before the component is mounted.

Close #46 #39

### CODE REVIEW

File: src/use-swr.ts [hunk 1]
```diff
@@ -116,7 +116,9 @@ function useSWR<Data = any, Error = any>(
   }
 
   // stale: get from cache
-  let [data, setData] = useState(useHydration() ? undefined : cacheGet(key))
+  let [data, setData] = useState(
+    config.suspense ? cacheGet(key) : useHydration() ? undefined : cacheGet(key)
+  )
```
Comment (quietshu) [inline src/use-swr.ts]:
```suggestion
  )
  // it is fine to call `useHydration` conditionally here
  // because `config.suspense` should never change
```

**Comment by RobertBorg** [comment]
I think you intended for this fix to be part of 0.1.2 release but it's not afaik.

**Comment by quietshu** [comment]
Published `swr@0.1.5` 🎉
